name: Send email new RSS Feed items	
on:
  rss:
    url: http://feeds.feedburner.com/zhihu-daily
jobs:
  email:
    name: Post a email
    runs-on: ubuntu-latest
    steps:
      - name: Send mail
        uses: dawidd6/action-send-mail@v2
        with:
          server_address: smtphz.qiye.163.com
          server_port: 25
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          subject: ${{ on.rss.outputs.title }}
          # Literal body:
          body: ${{ on.rss.outputs.content }}
          # Read file contents as body:
          to: ${{secrets.TO_MAIL}}
          from: ${{secrets.MAIL_USERNAME}} # <user@example.com>
          # Optional content type (defaults to text/plain):
          content_type: text/html
